### ISSUE TITLE
How to add stickers?

### ISSUE THREAD

**Issue by ThinkDevStudios** [laravel-notification-channels/telegram#100]
Hi! How do you add stickers on the message?

**Comment by irazasyed** [comment]
Hi,

You can use the `file($file, $type)` method to attach a [sticker](https://core.telegram.org/bots/api#sendsticker).

Ex:
```php
public function toTelegram($notifiable)
{
    return TelegramFile::create()
        ->to($notifiable->telegram_user_id) // Optional
        ->file('/path/to/sticker/file.webp', 'sticker'); 
}
```

Make sure the file is one of the compatible ones that are supported by Telegram. Refer their official documentation for more information.
