### ISSUE TITLE
Document not working

### ISSUE THREAD

**Issue by vladislavtkachenko** [laravel-notification-channels/telegram#104]
Laravel 8.20
Php 8.0.1

->document('https://file-examples.com/wp-content/uploads/2017/10/file-sample_150kB.pdf', 'sample.pdf')

The message with the file arrives but the file is corrupted and does not open.

->file(...)

works correct

**Comment by irazasyed** [comment]
That's because it seems like the file actually resides at this URL:

```
https://file-examples-com.github.io/uploads/2017/10/file-sample_150kB.pdf
```

The one you've shared simply redirects and Telegram servers may not be following the redirect and rather just trying to fetch and send as is. Try with a proper URL. It should work.

**Comment by vladislavtkachenko** [comment]
I tested other links as well) they are always corrupted

**Comment by vladislavtkachenko** [comment]
@irazasyed have you any ideas?

**Comment by rizkhal** [comment]
i have the same issue, i already try to use local and remote file but the file still corupt
