### ISSUE TITLE
The `->document()` nethod not working

### ISSUE THREAD

**Issue by vladislavtkachenko** [laravel-notification-channels/telegram#105]
Laravel 8.20
Php 8.0.1

->document('https_path_to_file', 'sample.pdf')

The message with the file arrives but the file is corrupted and does not open.

->file(...)

works correct

**Comment by MohammaddReza** [comment]
in laravel 8 get the same error when attaching a photo
Call to undefined method NotificationChannels\Telegram\TelegramMessage::file()

**Comment by irazasyed** [comment]
> in laravel 8 get the same error when attaching a photo Call to undefined method NotificationChannels\Telegram\TelegramMessage::file()

That method is only available in `TelegramFile::create()`

**Comment by irazasyed** [comment]
Latest release should fix this issue. Please create a new issue ticket if issue persist. Thanks!
