### ISSUE TITLE
How can I add proxy to Laravel Telegram Notification

### ISSUE THREAD

**Issue by falahatiali** [laravel-notification-channels/telegram#108]
telegram is not accessible in my country and I want to send notification to my channel. with vpn is everything good but without it I cant,
in Laravel notification website tell that we can use this help
```
https://docs.guzzlephp.org/en/stable/quickstart.html#environment-variables
```
But i dont understand how we can set a proxy.

**Comment by irazasyed** [comment]
Set the `HTTPS_PROXY` env var with your HTTPS proxy values in your Laravel `.env` file and it should pick up and work.
