### ISSUE TITLE
Method ->to() on TelegramMessage::class doesn't exists

### ISSUE THREAD

**Issue by GabrielFrohlich** [laravel-notification-channels/telegram#109]
In the docs, we have the code:
`
public function toTelegram($notifiable)
    {

        $url = url('/invoice/' . $this->invoice->id);
        return TelegramMessage::create()
            // Optional recipient user id.
            ->to($notifiable->telegram_user_id)
            // Markdown supported.
            ->content("Hello there!\nYour invoice has been *PAID*")
            
            // (Optional) Blade template for the content.
            // ->view('notification', ['url' => $url])
            
            // (Optional) Inline Buttons
            ->button('View Invoice', $url)
            ->button('Download Invoice', $url);
    }`
    
But in the TelegramMessage::class the method to() doesn't exists.

**Comment by hyptrance** [comment]
si am also having this issue in the latest laravel.

**Comment by irazasyed** [comment]
What version of the package do you use? Please mention that and the Laravel version.
