### ISSUE TITLE
Driver [telegram] not supported

### ISSUE THREAD

**Issue by ITrunsDE** [laravel-notification-channels/telegram#115]
I get the following message for my project.

_Driver [telegram] not supported._

My version of the project is Laravel Framework 8.50.0

**Comment by maxroby** [comment]
Same issue

**Comment by maxroby** [comment]
I was using:
`return ['telegram'];`
changing to:
`return [TelegramChannel::class];`
does the job.

**Comment by ITrunsDE** [comment]
> I was using:
> `return ['telegram'];`
> changing to:
> `return [TelegramChannel::class];`
> does the job.

Thanks that works for me, too.

**Comment by alberto-bottarini** [comment]
Could you please update documentation?
