### ISSUE TITLE
Driver [telegram] not supported with Lumen

### ISSUE THREAD

**Issue by rvalitov** [laravel-notification-channels/telegram#124]
Hi! 
I'm using latest Lumen 8.2.7. I get error
> Driver [telegram] not supported.

I believe this issue is related with #115.
If I follow the advice from [there](https://github.com/laravel-notification-channels/telegram/issues/115#issuecomment-883494723):
> I was using:
return ['telegram'];
changing to:
return [TelegramChannel::class];
does the job.

then everything works perfectly fine!
Perhaps, it's a universal solution to refer to a class name? And therefore apply #116 ?

**Comment by irazasyed** [comment]
Hey @rvalitov,

I just tested this in Lumen and I think I know where the problem is.

You need to register the Telegram Channel's service provider manually in your `bootstrap/app.php` file since Lumen doesn't have auto-discovery support and doesn't auto-register the service providers of the package.

Here's a sample code.

```php
# bootstrap/app.php

// Make sure to create a "config/services.php" file and add the config from readme.
$app->configure('services');

# Then register the notification service providers.

// This is needed to register bindings of the dispatcher if you're going to use on-demand notifications, etc.
$app->register(Illuminate\Notifications\NotificationServiceProvider::class);

// Telegram Notification Channel service provider.
$app->register(NotificationChannels\Telegram\TelegramServiceProvider::class);
```

Hope that helps!

**Comment by rvalitov** [comment]
Sorry, this is not the reason. Sure I registered everything. If I didn't do that, then other types of errors would appear.

BTW it was me who reported [the typo](https://github.com/laravel-notification-channels/telegram/issues/56#issuecomment-952733471) how to register that 😉

**Comment by rvalitov** [comment]
To be specific I'm using version 0.6.0 of Telegram notification.

**Comment by irazasyed** [comment]
> Sorry, this is not the reason. Sure I registered everything. If I didn't do that, then other types of errors would appear.

I see. Well, I just tested on a fresh installation with `0.7.0` release and latest version of Lumen. Maybe give the latest version a try once?

> BTW it was me who reported [the typo](https://github.com/laravel-notification-channels/telegram/issues/56#issuecomment-952733471) how to register that 😉

Ah I see. That's good.

I went ahead and added these instructions to the [readme](https://github.com/laravel-notification-channels/telegram#using-in-lumen) too.

**Comment by irazasyed** [comment]
Please try `0.7.0` and let me know if you're still facing this issue. You should debug this more perhaps. 

If issue persists, then I think we can change the instructions although I would like to understand where the core issue is.
