### ISSUE TITLE
Globally replace the recipient and expand the message

### ISSUE THREAD

**Issue by tschni** [laravel-notification-channels/telegram#126]
Hi all!

Is it possible to define in a global place which recipient chat id should be used and append something to the content?

Background: In the development environment I want all messages to be sent to me.
In the message should be additionally mentioned at the end something like "Original recipient chat: (id here)".

Thanks
Tobi

**Comment by irazasyed** [comment]
Hi,

Yes. You can make use of the 'to' method as mentioned in docs to overwrite the chat ID on-demand. 

You can access the original using the notifiable data your notification class receives and append it to the message. 

Please refer docs. 

Hope that helps!

**Comment by tschni** [comment]
Hi,

I had taken this from the documentation so far, for me it is more about whether I can set this globally at some point (maybe in a event?), so that I do not have to consider this with each notification.

Thanks.

**Comment by irazasyed** [comment]
You can make use of on-demand notifications as well in that case.

There are n number of ways. The channel itself is pretty flexible not only to set the recipients chat ID on-fly but also bot token for specific cases, if required.

**Comment by tschni** [comment]
I am already aware of this, but is it possible to overwrite the recipient globally, e.g. within an event?

The background is that the Telegram messages are normally sent directly to the user. But during the development all Telegram messages should be sent to a group from me.

**Comment by irazasyed** [comment]
No. There are no direct methods to do that from the channel's end.
