### ISSUE TITLE
Sending Long Message

### ISSUE THREAD

**Issue by malohtie** [laravel-notification-channels/telegram#127]
Hi
sometimes when sending a long message this exception is raised: Telegram responded with an error `400 - Bad Request: message is too long`
this error occur when message it longer than 4096 characters
```php
public function toTelegram($notifiable)
{

    return TelegramMessage::create()
        ->content(str_repeat('a', 4097));
}
```
can we improve this by spliting messages by 4096 characters ?
thanks

**Comment by irazasyed** [comment]
Hey!

I've added a new method called `chunk($limit = 4096)` to the `TelegramMessage` class.

Can you please test and let me know if it works fine for you?

You'll need to install the master branch. The default limit is 4096 chars but if you wish, you can set it to any number up to 4096 max.

If the message is longer than the chunk size you set, it'll split and send one by one per second (based on rate limitation requirements from Telegram). 

I'll tag a release if you confirm its working fine!

**Comment by malohtie** [comment]
Hey,
Yes it working and everything is fine
Thanks for your support

**Comment by irazasyed** [comment]
Great. New version released: https://github.com/laravel-notification-channels/telegram/releases/tag/0.8.0
