### ISSUE TITLE
Add Get Updates Support

### ISSUE THREAD

**Issue by irazasyed** [laravel-notification-channels/telegram#132]
I think we should consider adding a `getUpdates()` method so it's easier for new users to fetch updates of their bot and to retrieve chat ID for further processing.

Right now we don't provide any methods to retrieve chat IDs and have left that task to the end developer and someone who is very new to Telegram Bot API may find the usage instructions a bit incomplete since the channel expects them to have the chat ID but doesn't say where and how to get one.

This could be a new addition for future releases. Open for discussions if anyone wants to add their ideas to improve the overall usage/development experience with Telegram Bot API. 

Of course, I want to keep this to its primary purpose, i.e. notification, and not end up adding too many methods making it complex to use.

**Comment by irazasyed** [comment]
@alexsoft @faissaloux Thoughts?

**Comment by faissaloux** [comment]
Is your idea making simpler way to retrieve chat id right! If so, I have the same idea but I'm just thinking of best way to do it. Maybe giving channel/user/group link and then we retrieve the chatId or something like this!!

Isn't `getUpdates()` wrong name for this purpose!! If I understood you wrong please explain

**Comment by irazasyed** [comment]
You got my idea correct. The main idea is to let you retrieve the chat ID.

`getUpdates()` is based on the official API name and would return all the updates/messages sent to your bot, so you can save its data including name/username/chat ID.

**Comment by irazasyed** [comment]
We can't fetch the chat ID by user link since the IDs are unique for each bot.

**Comment by faissaloux** [comment]
I'm talking about channels not bots.

Maybe we have a misunderstanding here, My idea was make retrieving chatId easier. I think your idea is to get informations about updates/messages sent to the bot. Right! If so, now `getUpdates()` make sense.

**Comment by faissaloux** [comment]
```php
TelegramUpdates::get()->limit(2);
```

![Screenshot from 2021-11-24 15-18-51](https://user-images.githubusercontent.com/60013703/143255308-aa214a57-68f6-477b-857e-84823c3f399a.png)

**Comment by alexsoft** [comment]
Let's imagine how we usually get those chat ids when we need to prepare for notifications sending?
We need to connect a Notifiable entity with a chat id. For this, we usually need some user interaction. So a user clicks the Start button in the Telegram bot. Either at this point, there will be a webhook triggered with a deeplink parameter or updates have to be retrieved by calling `getUpdates` method on API.
In both cases, we need to somehow parse the payload from Telegram and this starts to feel not be a concern of this library.

What we can do, introduce a method to which developer can provide [Update](https://core.telegram.org/bots/api#update) object, from which we would just retrieve chat id, no matter what update is given (just try all possible types of updates and provide first that is available).

Or for manual retrieval we could write a small cli script that would call `getUpdates` and then developer would just need to somehow get a chat id from the response and save it wherever they need.

**Comment by irazasyed** [comment]
@alexsoft Well, Having a method like `getUpdates` has many advantages like you could schedule a task to check every x min/hours for new messages to the bot, get the update, save the details/associate id to the user entity all automated while also continue to send notifications in another task.

The get updates method would simply return the json decoded response from Telegram with no changes, its raw data for further processing, and simply a call to the getUpdates endpoint.

**Comment by irazasyed** [comment]
@faissaloux That looks like a good start to me.

**Comment by faissaloux** [comment]
Should I open a draft PR for this! And we can work on it together if we have anything to add/change ...

**Comment by faissaloux** [comment]
@irazasyed Should I open a draft PR for this! And we can work on it together if we have anything to add/change ...

**Comment by irazasyed** [comment]
@faissaloux  Sure, please go ahead.
