### ISSUE TITLE
Laravel 9 support

### ISSUE THREAD

**Issue by oriceon** [laravel-notification-channels/telegram#140]
λ composer require laravel-notification-channels/telegram
Using version ^1.0 for laravel-notification-channels/telegram
./composer.json has been updated
Running composer update laravel-notification-channels/telegram
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires laravel-notification-channels/telegram ^1.0 -> satisfiable by laravel-notification-channels/telegram[1.0.0, 1.x-dev].
    - laravel-notification-channels/telegram[1.0.0, ..., 1.x-dev] require illuminate/contracts ^5.5 || ^6.0 || ^7.0 || ^8.0 -> found illuminate/contracts[v5.5.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.

You can also try re-running composer require with an explicit version constraint, e.g. "composer require laravel-notification-channels/telegram:*" to figure out if any version is installable, or "composer require laravel-notification-channels/telegram:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by irazasyed** [comment]
Released https://github.com/laravel-notification-channels/telegram/releases/tag/2.0.0
