### ISSUE TITLE
Return type of NotificationChannels\Telegram\TelegramMessage::jsonSerialize()

### ISSUE THREAD

**Issue by ttfbjij** [laravel-notification-channels/telegram#143]
`[2022-06-20 15:11:19] production.WARNING: Return type of NotificationChannels\Telegram\TelegramMessage::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/cp2806f7527/web/vendor/laravel-notification-channels/telegram/src/Traits/HasSharedLogic.php on line 146  `

**Comment by marcoboers** [comment]
I have the same issue. It was fixed in master but a new release hasn't been made yet.  
@irazasyed could you create a new release?

**Comment by Muetze42** [comment]
New Laravel versions have type declarations:
````php
    /**
     * Convert the object into something JSON serializable.
     */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
```

But old versions not:
````php
    /**
     * Convert the object into something JSON serializable.
     *
     * @return array
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
        return $this->toArray();
    }
```

@ttfbjij 
Update Laravel to version 9 or install a old version of this package. 

@marcoboers 
You should maybe separate the Laravel versions in the requirements?

**Comment by irazasyed** [comment]
I've made it compatible with [JsonSerializable](https://www.php.net/manual/en/jsonserializable.jsonserialize.php) as per PHP docs (i.e. `mixed`). Can anyone test and confirm? If it works, will tag.

**Comment by marcoboers** [comment]
Yes, that works. If you could tag it that would be great. 

The array return type [committed](https://github.com/laravel-notification-channels/telegram/commit/d41776c39f888cb7c6746bf25cdaf6fbc3a0b56e) by @Muetze42 was also working for me, however it was never tagged/released and therefor only worked if you put `dev-master` version in composer.json.

**Comment by irazasyed** [comment]
https://github.com/laravel-notification-channels/telegram/releases/tag/2.1.0
