### ISSUE TITLE
Could you clarify usage of Handling Response please ?

### ISSUE THREAD

**Issue by devzorg** [laravel-notification-channels/telegram#148]
Would like to see some samples for Laravel9

Actually wanna to know how to get callback buttons pressed by users

**Comment by irazasyed** [comment]
This package is designed to push notifications. If you want to create a proper chatbot, then you're better off using something like [telegram-bot-sdk](https://github.com/irazasyed/telegram-bot-sdk).

There is a method to get updates using the polling method, so you could still try but I wouldn't recommend it.

**Comment by devzorg** [comment]
yes but you have trait methods buttonCallback but there is no way to use it at this time
So I overrided it to add url param and could open some urls, but really wanna that it worked in background when user pressed
