### ISSUE TITLE
error CouldNotSendNotification

### ISSUE THREAD

**Issue by BehroozBvk** [laravel-notification-channels/telegram#15]
Hi I got the error I receive when running : 

> CouldNotSendNotification in CouldNotSendNotification.php line 48:
The communication with Telegram failed.

**Comment by irazasyed** [comment]
It could be network issues either from your end or Telegram's end.

**Comment by BehroozBvk** [comment]
I tested the software with local XAMPP is possible that this or https

**Comment by BehroozBvk** [comment]
You were right the problem of telegrams have been tested on the server
