### ISSUE TITLE
Exception handler

### ISSUE THREAD

**Issue by DanielSpravtsev** [laravel-notification-channels/telegram#155]
Hey! Is it possible to add additional information like telegram exception to data parameter of event?
It is also will be handy to have 'to' var in $data when used as on-demand 

I use this in case of deleting User telegram chats that have deleted their account or blocked bot to avoid spam of 'Chat not found' & 'User blocked bot' exceptions in logger 

Dispatcher: 
https://github.com/laravel-notification-channels/telegram/blob/602c289d7cb73ec300f1a2255ed17042e95fd710/src/TelegramChannel.php#L68

**Comment by irazasyed** [comment]
I'll explore. But feel free to send a PR if you've already figured this out :)

**Comment by iKlsR** [comment]
The timing of this is actually perfect, I needed a way to disable users who have telegram messages in their dashboard and have blocked the bot as these pollute our exceptions slack channel. Going to change composer to `master` for now but this is minor release worthy imo.

**Comment by DanielSpravtsev** [comment]
@irazasyed Any news about tagging new package version? 😄
