### ISSUE TITLE
Add support for multiple bots

### ISSUE THREAD

**Issue by MarienMupenda** [laravel-notification-channels/telegram#159]
I am facing the situation where I need to use the same package (projet) to set up multiple kind of notifications.

1. One for developers (DevBot) : notify on push event from github
2. Second for commercial people : notify on order placed
3. For custommer, notify on new arrivals.
4. etc ...

**Comment by irazasyed** [comment]
Use the token method described in the readme to send notifications from multiple bots to multiple users.
