### ISSUE TITLE
CouldNotSendNotification. cURL error 60: SSL certificate problem

### ISSUE THREAD

**Issue by rsidash** [laravel-notification-channels/telegram#164]
Hi,

I'm getting following errors:

>  NotificationChannels\Telegram\Exceptions\CouldNotSendNotification 
> 
>   The communication with Telegram failed. `GuzzleHttp\Exception\RequestException: cURL error 60: SSL certificate problem: self signed certificate in certificate chain (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://api.telegram.org/bot516004118:AAEKsPOlk4XKHOjtLtjGGiQhCno_fGVL/sendMessage in D:\Program Files\xampp\htdocs\roster-notifications-webservice\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:211

**Comment by irazasyed** [comment]
Refer https://github.com/guzzle/guzzle/issues/1935#issuecomment-371756738
