### ISSUE TITLE
Call to undefined method NotificationChannels\Telegram\TelegramMessage::file()

### ISSUE THREAD

**Issue by mayutheandev** [laravel-notification-channels/telegram#165]
![image](https://user-images.githubusercontent.com/66521798/214013697-b0f3ea20-3fcd-46eb-86ad-c9ad8feb51d1.png)

**Comment by irazasyed** [comment]
Read docs. TelegramMessage doesn't have that method. You should be using TelegramFile.

**Comment by mayutheandev** [comment]
In the document, I see this method.
![image](https://user-images.githubusercontent.com/66521798/214795937-8381a32e-c289-478d-a415-4688f1d1d11c.png)

**Comment by irazasyed** [comment]
Please look at the docs and the screenshot you shared. It should be `TelegramFile::create()`

**Comment by mayutheandev** [comment]
Oh I see, my missing, Thanks so much
