### ISSUE TITLE
Laravel 10 compatibility

### ISSUE THREAD

**Issue by arfr** [laravel-notification-channels/telegram#169]
Please increase the version of `"illuminate/notifications": "^9.0",` to 10

`  Problem 1
    - Root composer.json requires laravel-notification-channels/telegram ^3.0 -> satisfiable by laravel-notification-channels/telegram[3.0.0].
    - Only one of these can be installed: illuminate/notifications[v9.0.0, ..., v9.52.0], laravel/framework[v10.0.0]. laravel/framework replaces illuminate/notifications and thus cannot coexist with it.
    - laravel-notification-channels/telegram 3.0.0 requires illuminate/notifications ^9.0 -> satisfiable by illuminate/notifications[v9.0.0, ..., v9.52.0].
    - Root composer.json requires laravel/framework ^10.0 -> satisfiable by laravel/framework[v10.0.0].
`

https://laravel.com/docs/10.x/upgrade#updating-dependencies

**Comment by arfr** [comment]
Please confirm and accept it :)
https://github.com/laravel-notification-channels/telegram/pull/167

**Comment by irazasyed** [comment]
Merged. But I'm yet to test. If you can test this and let me know, I'll release a new version.

**Comment by arfr** [comment]
`arfr$ composer test
> vendor/bin/pest

   PASS  Tests\Feature\TelegramMessageTest
  ✓ it can return the payload as an array
  ✓ it can disable notification
  ✓ it can determine if the recipient chat id has not been set
  ✓ the notification message can be set
  ✓ it can set the parse mode
  ✓ the recipients chat id can be set
  ✓ it can attach a view as the content
  ✓ it can add one message per line
  ✓ an inline button with callback can be added to the message
  ✓ it can escape special markdown characters per line
  ✓ an inline button can be added to the message
  ✓ additional options can be set for the message
  ✓ laravel conditionable trait
  ✓ it accepts content when constructed
  ✓ it can set token
  ✓ the default parse mode is markdown
  ✓ it can chunk a long message into given size
  ✓ it can set the disable web page preview

   PASS  Tests\Feature\TelegramLocationTest
  ✓ additional options can be set for the message
  ✓ it can return the payload as an array
  ✓ the notification latitude can be set
  ✓ it can determine if the recipient chat id has not been set
  ✓ the recipients chat id can be set
  ✓ it can send a location
  ✓ it accepts content when constructed

   PASS  Tests\Feature\TelegramUpdatesTest
  ✓ it can return the payload as an array
  ✓ it can fetch latest update
  ✓ it can limit number of updates
  ✓ it can get updates
  ✓ it can add additional options

  Tests:  52 passed
  Time:   0.17s

   PASS  Tests\Feature\TelegramUpdatesTest
  ✓ it can return the payload as an array
  ✓ it can fetch latest update
  ✓ it can limit number of updates
  ✓ it can get updates
  ✓ it can add additional options

  Tests:  52 passed
  Time:   0.17s
`

**Comment by irazasyed** [comment]
Thanks. Released: https://github.com/laravel-notification-channels/telegram/releases/tag/4.0.0
