### ISSUE TITLE
The communication with Telegram failed

### ISSUE THREAD

**Issue by LesyaTT** [laravel-notification-channels/telegram#176]
![image](https://github.com/laravel-notification-channels/telegram/assets/104120539/583e1925-0cae-4f1f-b460-f394362a2be8)
![image](https://github.com/laravel-notification-channels/telegram/assets/104120539/3a482449-afb4-4a6b-b2f2-a6c35564b377)

**Comment by w01ki3** [comment]
> ![image](https://user-images.githubusercontent.com/104120539/240269193-583e1925-0cae-4f1f-b460-f394362a2be8.png) ![image](https://user-images.githubusercontent.com/104120539/240269312-3a482449-afb4-4a6b-b2f2-a6c35564b377.png)

Hi
At the end ->send(); You should add and try. It will be the solution for you.

**Comment by w01ki3** [comment]
Hi
At the end ->send(); You should add and try. It will be the solution for you.

**Comment by irazasyed** [comment]
- Post your logs.
- Check to make sure your server is able to connect to Telegram / is able to resolve the hostname.
- Are you behind VPN/Proxy? Make sure it's valid and working.

**Comment by irazasyed** [comment]
I notice your `toTelegram` method is static.
