### ISSUE TITLE
How to send to multiple Telegram bots

### ISSUE THREAD

**Issue by znau** [laravel-notification-channels/telegram#180]
Whether to support configuring multiple tokens?

# config/services.php

'telegram-bot-api' => [
    'token' => env('TELEGRAM_BOT_TOKEN', 'YOUR BOT TOKEN HERE')
],

**Comment by irazasyed** [comment]
Use the `token` method in your notification and pass the token dynamically (So you can send to n number of bots).

Read the docs [here](https://github.com/laravel-notification-channels/telegram?tab=readme-ov-file#shared-methods)
