### ISSUE TITLE
Error: Call to a member function toNotGiven() on null 

### ISSUE THREAD

**Issue by patake** [laravel-notification-channels/telegram#181]
Hello,

When I try to send notification, using this code:

`$telegram = TelegramMessage::create();`
`$telegram->to(config('services.telegram-bot-api.chat'))`
`$telegram->disableNotification(true);`
`$telegram->line($text);`
`$telegram->send();`

I receive this error:

Error: Call to a member function toNotGiven() on null in file /var/www/vendor/laravel-notification-channels/telegram/src/TelegramChannel.php on line 47

Any ideias to solve this?

Thanks

**Comment by irazasyed** [comment]
Share your full code. Are you sure you're returning the telegram object?

**Comment by benjibee** [comment]
I was seeing this same exception in my logs, though the notifications were being sent out. This was indeed because I was forgetting to return the Telegram class itself. This helped, thank you!
