### ISSUE TITLE
Latest Commit isn't included in a tagged version

### ISSUE THREAD

**Issue by bowett** [laravel-notification-channels/telegram#188]
Hi,

The latest commit which adds keyboards to messages doesn't install when you do a:

composer require laravel-notification-channels/telegram

I think this might be because the latest commit isn't in a tagged version i.e. 4.1 but I could be wrong on that.

So this documented example doesn't work:

```
public function toTelegram($notifiable)
{
    return TelegramPoll::create()
        ->to($notifiable)
        ->content('Choose an option:')
        ->keyboard('Button 1')
        ->keyboard('Button 2');
        // ->keyboard('send your number', request_contact: true)
        // ->keyboard('send your location', request_location: true);
}
```

results in an error:

```
 Error  Call to undefined method NotificationChannels\Telegram\TelegramPoll::keyboard().
```

Dan.

**Comment by irazasyed** [comment]
https://github.com/laravel-notification-channels/telegram/releases/tag/5.0.0
