### ISSUE TITLE
Expand TelegramMessage class

### ISSUE THREAD

**Issue by IvanovPavel** [laravel-notification-channels/telegram#194]
Could you add an extra parameter for the class `TelegramMessage` for `parse_mode`? 
At this moment, in the documentation, you can use `MarkdownV2`, but your code may not support it. 

Thanks in advance.

**Comment by Samoylenko666** [comment]
You can use escapedLine method maybe this will help

**Comment by irazasyed** [comment]
`parseMode()` is already supported. You may use the ParseMode enum to switch to one of the 3 supported ones. Refer docs.
