### ISSUE TITLE
Enhancement Request: Add Multi-file/Photo Sending Feature Using Telegram API's sendMediaGroup Method

### ISSUE THREAD

**Issue by ahmad-222** [laravel-notification-channels/telegram#199]
Thank you for creating this awesome package! It's both useful and beautifully designed.

I wanted to ask if it's possible to add a new feature that allows sending multiple files or photos in one message using the Telegram API's sendMediaGroup method: [sendMediaGroup API](https://core.telegram.org/bots/api#sendmediagroup).

I greatly appreciate your efforts in the free open-source community. Thank you very much!

**Comment by irazasyed** [comment]
Thanks for the kind words. Glad to know it's been useful. 

Unfortunately I'm currently occupied in other things, so won't be able to work on the new feature anytime soon. However, I'll be happy to review the PR if you create one and merge accordingly.

Appreciate the suggestion. Thanks.

**Comment by ahmad-222** [comment]
Thank you for your kind response to my request. 
I hope to make the necessary modifications to add this new feature. I would be happy to provide feedback on the code I write and hope it will be as beautifully crafted as the current code.
 Thank you very much
