### ISSUE TITLE
TelegramChannel not supported

### ISSUE THREAD

**Issue by physio** [laravel-notification-channels/telegram#20]
when i call an notification, the system answer as this:

NotificationChannels\Telegram\Exceptions\CouldNotSendNotification: You must provide your telegram bot token to make any API requests. in [...]/vendor/laravel-notification-channels/telegram/src/Exceptions/CouldNotSendNotification.php:38
Stack trace:
#0 [...]/vendor/laravel-notification-channels/telegram/src/Telegram.php(85): NotificationChannels\Telegram\Exceptions\CouldNotSendNotification::telegramBotTokenNotProvided('You must provid...')

**Comment by axd** [comment]
You've created your bot? When it's created Telegram gives you a token for usage.
