### ISSUE TITLE
can't send image

### ISSUE THREAD

**Issue by robertnicjoo** [laravel-notification-channels/telegram#22]
Hi,
I try to send post image with my notification but i cannot do it!

here is my code:

```
public function toTelegram($post)
     {
         return TelegramMessage::create()
             ->to('@studiotjd')
             ->content([
               'uri' => $post->title.' http://xxxxxxx.com/blog/article/'. $post->slug,
               'photo' => $post->image. 'http://xxxxxxx.com/images/'. $post->image,
               'text' => $post->title,
             ]);
     }
```

I'm getting error of:

> Telegram responded with an error `400 - Bad Request: message text is empty`

**Comment by alexsoft** [comment]
Hello, @robertnicjoo. This package only supports text notifications.

**Comment by robertnicjoo** [comment]
Hello @alexsoft , thanks for responding. Is there any way that I can include image support?

**Comment by irazasyed** [comment]
@robertnicjoo You can use the [alternate](https://github.com/laravel-notification-channels/telegram#alternatives) option for image and or any other Telegram methods.
