### ISSUE TITLE
How to avoid toTelegram Function

### ISSUE THREAD

**Issue by skalero01** [laravel-notification-channels/telegram#23]
Hi, i'd like to know how to ignore toTelegram function

I have the next code

```php
public function toTelegram($notifiable)
    {
        $msg = $this->message($notifiable);
        return TelegramMessage::create()
            ->to($notifiable->{$this->telegram_object}->telegram_id)
            ->content($msg['message'])
            ->button($msg['button_text'], $msg['url']);
    }
```

But i'd like to validate if telegram id exist, and in case it doesnt dont send anything. But i get an error if a dont return anything or if i send it empty

```php
public function toTelegram($notifiable)
    {
        $msg = $this->message($notifiable);
        if(!isset($notifiable->{$this->telegram_object}->telegram_id))
            return;
        return TelegramMessage::create()
            ->to($notifiable->{$this->telegram_object}->telegram_id)
            ->content($msg['message'])
            ->button($msg['button_text'], $msg['url']);
    } 
```

What code should i put to just ignore and dont try to send anything? If there isnt any way could you please add a method to do this?

Regards

**Comment by irazasyed** [comment]
Try doing that in your `via` method? Validate and if it passes, then append the channel or ignore. Lmk if it works.

**Comment by irazasyed** [comment]
You can also validate prior to calling the notify method. And if it passes, only then you notify.

**Comment by skalero01** [comment]
its not anyway to make it on ToTelegram function? will save a lot of code for me :( Regards

**Comment by irazasyed** [comment]
I don't think so. Also, I don't see much code either. It's easier if you do it in your `via` method.
