### ISSUE TITLE
Multiple Telegram Bot Token 

### ISSUE THREAD

**Issue by shiroamada** [laravel-notification-channels/telegram#26]
Is it possible to set multiple telegram bot token? If yes, can let me know how to do it in notification class?

Thanks!

**Comment by irazasyed** [comment]
You can use the `config` to set a token at runtime.

Ex: `config(['services.telegram-bot-api.token' => 'Your Bot Token']);`

You can place this in your AppServiceProvider or your Notification class (Constructor) or anywhere as long as it gets executed before your notification is triggered.

**Comment by blaqdog** [comment]
This is not working for me. I have laravel 5.8, and when I tried to change token with config like this:
```
class TelegramReportBot extends Notification //implements ShouldQueue
{
	public function __construct()
    {
    	config(['services.temporary-remember-config-parameter.telegram-bot-api.token' => config('services.telegram-bot-api.token')]);
    	config(['services.telegram-bot-api.token' => config('services.telegram-bot-api.report-bot-token')]); 
    }

public function __destruct()
    {
    	config(['services.telegram-bot-api.token' => config('services.temporary-remember-config-parameter.telegram-bot-api.token')]);
    }

```
All of my notifications via telegram including other classes start to mixing and sending messages with wrong token

**Comment by blaqdog** [comment]
Seems it works only if the Job class and Notification itself do not implements ShouldQueue interface

**Comment by camiant** [comment]
> Seems it works only if the Job class and Notification itself do not implements ShouldQueue interface

is there a way to make it work?

**Comment by camiant** [comment]
@irazasyed any chance to get this fixed?
