### ISSUE TITLE
send message to a user

### ISSUE THREAD

**Issue by amoopoori** [laravel-notification-channels/telegram#28]
hi 
i want to send message to a user for example @Ahmadreza 
i cant do it
please help me

**Comment by kslr** [comment]
Available Message methods
- to($chatId): (integer) Recipient's chat id.
- content(''): (string) Notification message, supports markdown. For more information on supported markdown styles, check out these docs.
- button($text, $url): (string) Adds an inline "Call to Action" button. You can add as many as you want and they'll be placed 2 in a row.
- options([]): (array) Allows you to add additional or override sendMessage payload (A Telegram Bot API method used to send message internally). For more information on supported parameters, check out these docs.

https://github.com/A3sal0n/FalconGate/wiki/Get-Telegram-Chat-ID

**Comment by irazasyed** [comment]
You need to store that user's telegram ID in your database.

**Comment by amoopoori** [comment]
Thanks

در تاریخ ۸ فوریهٔ ۲۰۱۸ ۹:۴۹ ب.ظ، "Syed Irfaq R. ⚡️" <
notifications@github.com> نوشت:
