### ISSUE TITLE
Call to a member function toNotGiven() on boolean

### ISSUE THREAD

**Issue by AGhasemzadeh** [laravel-notification-channels/telegram#32]
Hello,
    public function toTelegram($notifiable)
    {
        $pay = route('invoice.pay-link-password', [$this->invoice->id,$this->invoice->password]);
        $view = route('invoice.view-password', [$this->invoice->id,$this->invoice->password]);
        if($this->user->telegram_user_id) {
            return TelegramMessage::create()
                ->to($this->user->telegram_user_id)
                ->content("صدور فاکتور جدید:" . $this->invoice->id ."\n" ."مبلغ فاکتور:" . number_format($this->invoice->total) ."\n") // Markdown supported.
                ->button('نمایش فاکتور', $view)
                ->button('پرداخت فاکتور', $pay);
        } else {
            return false;
        }
    }

And my usage is:
        $invoice = Invoice::findOrFail(1);
        $user = Auth::user();
        try {
            Notification::send($user, new InvoiceCreated($invoice, $user));
        } catch (\Exception $e) {}

But I get : 
Call to a member function toNotGiven() on boolean
vendor/laravel-notification-channels/telegram/src/TelegramChannel.php

**Comment by alexsoft** [comment]
@AGhasemzadeh you get into case when `$this->user->telegram_user_id` is false, you return false, but you have to return instance of TelegramMessage. That's why you get this error. I would recommend in case if `$this->user->telegram_user_id` is false, throw an exception.

**Comment by makuser** [comment]
> I would recommend in case if $this->user->telegram_user_id is false, throw an exception.

Lots of us used the  if($this->user->telegram_user_id) {...} clause to test whether a telegram_user_id had been set or not. Not every application user has Telegram or connected the app to Telegram, and thus such a switch is necessary.
Every single other laravel-notification-channel library does this automatically and DOES NOT THROW any exception if the user has not connected/subscribed to a specific notification channel.

Please have a look at #31 to understand why it was necessary to use in the first place.

**Comment by makuser** [comment]
> @makuser So you're saying we should just silently ignore and not throw an exception?
> 
> I'm fine with that but then it becomes difficult to debug I suppose.

Great that you changed your mind and this is finally "fixed" with #75 in 0.4.0.
