### ISSUE TITLE
html support

### ISSUE THREAD

**Issue by robertnicjoo** [laravel-notification-channels/telegram#33]
Hi does this package support html tags?

e.g. using `<br>` or `<p>` tags in `->content()` notification that will send?

**Comment by Cawa-Kubica** [comment]
We can send HTML to the Telegram but the only tags that are allowed are bold, strong, italic, emphasis, anchor, code and preformatted tag.
Markdown tags example:
return TelegramMessage::create()
            ->to()
            ->content('*' . $news->title . '*' . "\n\n" . $news->preview_text)
            ->options(['parse_mode' => 'markdown']);

Docs: https://core.telegram.org/bots/api#html-style
