### ISSUE TITLE
no way to attach a photo?

### ISSUE THREAD

**Issue by huglester** [laravel-notification-channels/telegram#34]

**Comment by ALiSHERBE** [comment]
+1

**Comment by robertnicjoo** [comment]
same issue here

**Comment by irazasyed** [comment]
As of now, no! You can either use the SDK or feel free to send a PR with this feature added as unfortunately, I don't have time right now. Thanks for the suggestion.

**Comment by syropian** [comment]
I'm getting `Call to undefined method NotificationChannels\Telegram\TelegramMessage::file()`. Are we sure it was implemented properly?
