### ISSUE TITLE
Ability to change button columns in a row

### ISSUE THREAD

**Issue by Lotuashvili** [laravel-notification-channels/telegram#35]
Hi.

I was reading a source code and found that `button()` function splits buttons as 2 columns in a row. Will be good if we can change column numbers in a row.

From **src/TelegramMessage.php:78**
```
$replyMarkup['inline_keyboard'] = array_chunk($this->buttons, 2);
```

**Comment by irazasyed** [comment]
Please feel free to send a PR and will merge it. Thanks!
