### ISSUE TITLE
cant send file

### ISSUE THREAD

**Issue by mobin00619** [laravel-notification-channels/telegram#47]
when i want use file() method, say :

Call to undefined method NotificationChannels\Telegram\TelegramMessage::file();

**Comment by irazasyed** [comment]
You need to use `TelegramFile` to send a file. Please refer [TelegramFile](https://github.com/laravel-notification-channels/telegram/blob/master/src/TelegramFile.php).

**Comment by alfredobarron** [comment]
How to use both TelegramFile and TelegramMessage?
