### ISSUE TITLE
Need create tag 0.0.6 to can use TelegramFile

### ISSUE THREAD

**Issue by alfredobarron** [laravel-notification-channels/telegram#48]

**Comment by atymic** [comment]
@irazasyed it seems laravel 6 support and this isn't tagged yet. Are you able to do that?
Thanks!

**Comment by atymic** [comment]
@irazasyed Are you ok with me tagging a new release for laravel 6 support + this feature? (or you can do it)

**Comment by irazasyed** [comment]
@atymic Allow me a day or two and I'll tag it. I need to test this properly and revise the docs as it seems like there is an issue due to past PRs. So I don't want to tag this just yet.

Been extremely busy, so was not able to do it. Sorry!

**Comment by atymic** [comment]
No worries 😄 

Thanks!

**Comment by atymic** [comment]
@irazasyed 

Did you get a chance to tag this?
Thanks!

**Comment by irazasyed** [comment]
@atymic Done!

**Comment by atymic** [comment]
Thanks!
