### ISSUE TITLE
Chat not found

### ISSUE THREAD

**Issue by v-bubar** [laravel-notification-channels/telegram#49]
I keep on getting `CouldNotSendNotification` Exception with message `Telegram responded with an error 400 - Bad Request: chat not found`.

My `toTelegram` method is pretty straightforward

```
public function toTelegram($notifiable)
    {
        return TelegramMessage::create()
                              ->to($this->target)
                              ->content($this->message);
    }
```
where `$this->target` is the chat_id and `$this->message` is the message.

Chat_id exists, in fact it's me, and I've already started the conversation with the bot via App.

**Comment by vkabachenko** [comment]
I've got the same error too

**Comment by irazasyed** [comment]
I just tested on a fresh installation and everything seems to be working fine.

Please make sure `$this->target` isn't empty?

**Comment by webspilka** [comment]
@v-bubar do you resolve this problem ?
I have same error if chat is private. But if I make it public - all works.
Tell me, who knows why the bot can’t send messages to a private channel, even though it is the admin of this channel?
