### ISSUE TITLE
Send messages to a group (bot integrated in this group)

### ISSUE THREAD

**Issue by rafalilloblanco** [laravel-notification-channels/telegram#54]
Good afternoon I would like to be able to send messages to a group where the bot is integrated as an administrator, so that all users of that group can read the notification. it's possible?

This is my code

`public function toTelegram($notifiable)
    {
        $usuario = User::where('id', $this->comentario->user_id)->value('name');
        $servicio = Servicio::where('id', $this->comentario->servicio_id)->value('titulo');
        $descripcion = $this->comentario->descripcion;

        return TelegramFile::create()
            ->to(189399173)
            ->file('../public/img/logo.jpg', 'photo')
            ->content("¡Hola! *". $usuario. "* ha escrito el siguiente *comentario*:\n\n". $descripcion . "\n\n*Servicio:* ". $servicio);
            //->button('Ver notificaciones', $url);
    }`

**Comment by rafalilloblanco** [comment]
`chat": {
          "id": -259964816,
          "title": "ReparaApp",
          "type": "group",
          "all_members_are_administrators": true
        },`

For example, I put the id of my user and without problem send me the message, but then the group id appears with a "-" sign in front of me and when I put it, it doesn't give me any message but I don't receive the message in telegram .

The bot is in a group and has administrator permissions.

**Comment by rafalilloblanco** [comment]
I have managed to send it to the group where the bot is but if now I also want to add another id, is there a way to add several receivers?

**Comment by rafalilloblanco** [comment]
For example, receive it in the group and also receive it personally.

**Comment by irazasyed** [comment]
So I just tested by adding my bot to a test group and here's now you should be doing:

```php
return TelegramMessage::create()
        ->to('-259964816')
        ->content('Hello World');
```

**Comment by irazasyed** [comment]
To send to several recipients, you can use the routing method. Please [refer](https://github.com/laravel-notification-channels/telegram#routing-a-message).

**Comment by rafalilloblanco** [comment]
'public function routeNotificationForTelegram()
{
    return $this->telegram_user_id;
}'

Could you replace this code with an array? That is, could you do this?

'public function routeNotificationForTelegram()
{
    return [id1,id2,id3];
}'

**Comment by irazasyed** [comment]
## Recommended method

> Using routes method. Make sure there is a `routeNotificationForTelegram()` in your notifiable model.

```php
foreach($recipients as $recipient) {
	$recipient->notify(new TestNotification());
}
```

## Alternate

> If you don't have a notifiable model.

```php
use App\Notifications\TestNotification;
use Illuminate\Support\Facades\Notification;


$recipients = ['123456789', '-259964816', 'any more ids...'];
foreach($recipients as $recipient) {
	Notification::route('telegram', $recipient)->notify(new TestNotification());
}
```

Hope that helps!

**Comment by irazasyed** [comment]
@rafalilloblanco You can't provide an array. Only one ID but you can loop through your notifiables and send everyone your notification. Please refer [Notifications docs](https://laravel.com/docs/6.x/notifications) to understand how everything works.
