### ISSUE TITLE
Best practice retrieving Telegram ID

### ISSUE THREAD

**Issue by axtg** [laravel-notification-channels/telegram#55]
This is more of a question, but I'm looking for inspiration how to connect a user's Telegram ID with my Laravel installation. No user will ever know their ID, plus it is spam sensitive. So I would think...

1. Create two temporary tokens in database 
2. Show first token on website to user
3. Instruct user to tell first token to my bot in Telegram
4. Laravel store ID and sends (via notification) the second token to user
5. User enters second token on website to close the loop (setting verified in DB to true)

This would - to me - resemble a proper opt-in process for Telegram. Thoughts? Ideas?

**Comment by irazasyed** [comment]
You can make use of the [Deep linking](https://core.telegram.org/bots#deep-linking) feature Telegram offers.

Generate a unique token, show them a link and let the user start the bot with it. Once you get the start payload, you can associate the Telegram account with the user's account in your app.

Just make sure you revoke that token after associating the accounts. If the user wants to link to a new account, you can generate a new token (perhaps it could expire when the entire process is done so it's always unique).

**Comment by irazasyed** [comment]
In addition to the above, if you want to have the user confirm the opt-in (or rather double opt-in), you can perhaps show them a nice response from your bot as soon as you get the start payload telling them if they're sure they want to link this Telegram with the account in your app for notifications and an inline button with a callback query to confirm the same so it's easier to process or you could have an expiring external link too (again with a unique token).

While this isn't really required but it'll be more explicit in case if the user wasn't sure when they just clicked on the bot link in your app. Just an idea.

**Comment by axtg** [comment]
Appreciate you thinking along, thanks for the inspiration!
I'm assuming this will require me to use the SDK instead. So I'll look at that one now.
