### ISSUE TITLE
Lumen 5.8

### ISSUE THREAD

**Issue by circlefind** [laravel-notification-channels/telegram#56]
This support for lumen 5.8?
If can how to configure it
Please help

**Comment by irazasyed** [comment]
Lumen doesn't have notification system, does it?

**Comment by circlefind** [comment]
Yes right, but i have added laravel notification to lumen and telegram bot token in config/service
result message error : You must provide your telegram bot token to make any API requests

Must use Laravel for this package or have another solution?
Thanks for reply @irazasyed

**Comment by irazasyed** [comment]
You need to register the service provider in that case but I have never tested this with Lumen. So I can't really give you the right solution, you should probably test and let us know.

Laravel is the best to use these notification channels, tho.

**Comment by NRDeshpande** [comment]
I know this is closed but in case someone wanted help on this. I had the same issue but i am able to enable the Telegram notification for Lumen 6.0.*.

After registering NotificationServiceProvider in bootstrap/app.php, i have created service.php in my custom config folder and added
`
'telegram-bot-api' => [
      'token' => env('TELEGRAM_BOT_TOKEN')
 ]
`

and in bootstrap/app.php
`
 $app->configure('service.php');
`

Finally registering TelegramServiceProvider in bootstrap/app.php worked for me.
`
$app->register(NotificationChannels\Telegram\TelegramServiceProvider::class);
`

**Comment by NakatoTeshika** [comment]
@NRDeshpande Hello, did you do something else when you had a problem with that, because I did it and nothing changed, I have the same error

**Comment by irazasyed** [comment]
New instructions were added to README. [Using in Lumen](https://github.com/laravel-notification-channels/telegram#using-in-lumen) for future reference.
