### ISSUE TITLE
Error 500 un hosting

### ISSUE THREAD

**Issue by rafalilloblanco** [laravel-notification-channels/telegram#57]
Hi, when I send a notification locally, the bot works perfectly.  When uploading the project to my hosting, it gives me error 500 and tells me message error.

**Comment by irazasyed** [comment]
Check your file permissions?

Share your code, please. Without that, it's super difficult to figure out the issue.

**Comment by atymic** [comment]
Also, share the actual error message you are getting please.

**Comment by rafalilloblanco** [comment]
`    public function toTelegram($notifiable)
    {
        $usuario = User::where('id', $this->comentario->user_id)->value('name');
        $servicio = Servicio::where('id', $this->comentario->servicio_id)->value('titulo');
        $descripcion = $this->comentario->descripcion;

        return TelegramFile::create()
            //https://api.telegram.org/botBOT_TOKEN/getUpdates
            ->to('your_id') //Grupo de Telegram
            ->file('../public/img/logo.jpg', 'photo')
            ->content("¡Hola! *". $usuario. "* ha escrito el siguiente *comentario*:\n\n". $descripcion . "\n\n*Servicio:* ". $servicio);
    }`

This is my code

**Comment by rafalilloblanco** [comment]
![Captura](https://user-images.githubusercontent.com/17000368/68283494-ee776180-007b-11ea-9cba-419dc71b6790.JPG)

Here you have a screenshot of the error that appears to me. It only appears when I upload my project to the hosting, but instead it works without problems.

**Comment by atymic** [comment]
You'll need to check your `laravel.log` file for the actual error. Did you add your creds to the ENV file on the server?

**Comment by rafalilloblanco** [comment]
This is the error that appears in the file laravel.log
--------------------------------------------------------------------------------------------------------------

[2019-11-06 09:55:51] production.ERROR: Telegram responded with an error `400 - Bad Request: wrong HTTP URL specified` {"userId":1,"exception":"[object] (NotificationChannels\\Telegram\\Exceptions\\CouldNotSendNotification(code: 0): Telegram responded with an error `400 - Bad Request: wrong HTTP URL specified` at /home/reparapp/vendor/laravel-notification-channels/telegram/src/Exceptions/CouldNotSendNotification.php:31)
[stacktrace]

#0 /home/reparapp/vendor/laravel-notification-channels/telegram/src/Telegram.php(145): NotificationChannels\\Telegram\\Exceptions\\CouldNotSendNotification::telegramRespondedWithAnError(Object(GuzzleHttp\\Exception\\ClientException))

#1 /home/reparapp/vendor/laravel-notification-channels/telegram/src/Telegram.php(104): NotificationChannels\\Telegram\\Telegram->sendRequest('sendPhoto', Array, false)

#2 /home/reparapp/vendor/laravel-notification-channels/telegram/src/TelegramChannel.php(59): NotificationChannels\\Telegram\\Telegram->sendFile(Array, 'photo', false)

**Comment by irazasyed** [comment]
Looks like you've given a local path to your file. You need to define an absolute path to your local file. It won't resolve automatically if you provide `../public/img/logo.jpg`

Try with this ex: `public_path('img/logo.jpg')`

Make sure the file is readable.

**Comment by rafalilloblanco** [comment]
I have put just what you tell me and I still see the same error.

![Captura](https://user-images.githubusercontent.com/17000368/68585390-67165d80-0482-11ea-9f66-756b78be77bc.JPG)

**Comment by irazasyed** [comment]
Disable file upload and first test if a normal notification is going through or not?

If it is, then the issue is somewhere related to your file. It could be anything from file permissions to the path to file and so on. Also, please clear logs and re-post after all the tests.
