### ISSUE TITLE
CURL 35 error  Exception CouldNotSendNotification

### ISSUE THREAD

**Issue by AshutoshJha15** [laravel-notification-channels/telegram#61]
i am getting CouldNotSendNotification

my code is 

    public function toTelegram($post)
    {
        return TelegramMessage::create()
            ->to('@ExamaholicBot')
            ->content('Hello ');
    }

![image](https://user-images.githubusercontent.com/50516423/68415085-8e85d580-01b7-11ea-970f-9cbc89f97084.png)

**Comment by irazasyed** [comment]
Check your OpenSSL installation? Seems like you're unable to connect to Telegram.

**Comment by AshutoshJha15** [comment]
![image](https://user-images.githubusercontent.com/50516423/68472883-8b3a2a80-0247-11ea-814c-1f2fb75e79de.png)

**Comment by irazasyed** [comment]
Were you able to resolve the issue?

Can you try pinging the Telegram domain and see if you're able to connect?

It could be firewall. Hard to debug but def. something is preventing you from connecting the API server.

**Comment by Lloople** [comment]
I don't know if it's because of this, but I always use the Telegram ID instead of the username for sending messages, found here:

```json
{
  "update_id": 143932748,
  "message": {
    "message_id": 159256,
    "from": {
      "id": 4256599, <-- This one
      "is_bot": false,
      "first_name": "David",
      "last_name": "Llop",
      "username": "Lloople",
      "language_code": "es"
    }
}
```
