### ISSUE TITLE
token

### ISSUE THREAD

**Issue by giorg** [laravel-notification-channels/telegram#64]
Hi,
I did set my token in config/services.php:

``'telegram-bot-api' => [
        'token' => env('TELEGRAM_BOT_TOKEN', '<I_did_put_my_token_here>')
    ]``

but when I try to send a request

``public function toTelegram($notifiable)
    {
        return TelegramMessage::create()
            ->to(22919823)
            ->content("Hello there!\nYour invoice has been *PAID*");
    }``

I get this error:

> You must provide your telegram bot token to make any API requests

what am I doing wrong?
thanks

**Comment by irazasyed** [comment]
Hey!

Please make sure the config is not cached and if it is, then clear it.

Also, instead of setting the token directly there. I would suggest you set an env var `TELEGRAM_BOT_TOKEN=YOURTOKEN` in your `.env` file.

See if that helps?

**Comment by giorg** [comment]
the damn cache, I always forget that ^^"
Thanks a lot for your excellent work!
