### ISSUE TITLE
I get the null value response

### ISSUE THREAD

**Issue by mr-ghomi** [laravel-notification-channels/telegram#66]
How do I get enough message_id?

**Comment by irazasyed** [comment]
Can you elaborate, please?

**Comment by VladimirBerdnik** [comment]
@irazasyed , I mean it's about this: https://github.com/laravel-notification-channels/telegram/pull/67 (in progress)

**Comment by irazasyed** [comment]
Should be resolved now with #67. I will tag shortly after I test. Thanks, @VladimirBerdnik.

**Comment by VladimirBerdnik** [comment]
@irazasyed , thank you for quick answer and release!
