### ISSUE TITLE
On-Demand Notifications

### ISSUE THREAD

**Issue by AntonLugtenburg** [laravel-notification-channels/telegram#69]
Hello Guys, 
I could not find any information about this, but "on Demand" is not supported for Telegram Notifications right ?

https://laravel.com/docs/5.8/notifications#on-demand-notifications

It would be great to post existing Notifications also to groups or channels. 
Is there a way to do this with like this ?

`
Notification::route(TelegramChannel::class, env('TELEGRAM_ADMIN_CHAT_ID'))
                    ->notify(new NOTIFICATION($data));
`
`
Notification::route('telegram', env('TELEGRAM_ADMIN_CHAT_ID'))
                    ->notify(new NOTIFICATION($data));
`

Thank you

**Comment by irazasyed** [comment]
Hey @AntonLugtenburg,

On-demand notifications are supported by any notification channel. There is no special requirement. It's simply an anonymous notifiable class.

This should work

```php
Notification::route(\NotificationChannels\Telegram\TelegramChannel::class, 'TELEGRAM_CHAT_ID')
            ->notify(new InvoicePaid($invoice));
```

Also, You can pass any valid Telegram chat ID that has interacted with your bot (So that can be user, group, or channel).

**Comment by AntonLugtenburg** [comment]
Thank you very much for your time and answering. Its working very nicely. Thanks again and have a good time

**Comment by AntonLugtenburg** [comment]
Sorry to bother you again, but i know the issue now and i would appreachiate your help.
Notifications work, but if i specify a channel other than telegram on a On-Demand Notification that has also telegram class in the via method, it throws an error that the telegram id is missing. 

`Notification::route('slack',` env('HOOK'))->notify(new `Notification($model));`

` public function via($notifiable)
    {
        return ['mail', TelegramChannel::class, 'slack'];

    }`

Do i understand something wrong ? If u remove telegram from the channels it works by only sending mail or slack message..

Thanks again
