### ISSUE TITLE
On-Demand/AnonymousNotifiable will not route with TelegramChannel::class

### ISSUE THREAD

**Issue by matical** [laravel-notification-channels/telegram#72]
AnonymousNotifiable only uses a basic assoc array to lookup routes. When you're routing with `Notification::route(TelegramChannel::class, 'token')`, you'll get something like
```php
Illuminate\Notifications\AnonymousNotifiable^ {
  +routes: array:1 [
    "NotificationChannels\Telegram\TelegramChannel" => <token>
  ]
}
```
instead of
```php
Illuminate\Notifications\AnonymousNotifiable^ {
  +routes: array:1 [
    "telegram" => <token>
  ]
}
```
so [`! $to = $notifiable->routeNotificationFor('telegram')`](https://github.com/laravel-notification-channels/telegram/blob/bd1d67ca83e16e634759c3bf8b807ee699636865/src/TelegramChannel.php#L47) will always throw.

You can either update the on-demand documentation to only use the string "telegram" or check for an instance of `AnonymousNotifiable` and do something like 
`$notifiable->routeNotificationFor(TelegramChannel::class)`.

**Comment by irazasyed** [comment]
Good catch, will revise README. Thank you!
