### ISSUE TITLE
Driver [NotificationChannels\Telegram\TelegramChannel] not supported for Queued Notification

### ISSUE THREAD

**Issue by mauronex** [laravel-notification-channels/telegram#73]
Hello everybody,
i installed the notification channel following the instructions provided.

I receive the following errors:
Driver [NotificationChannels\Telegram\TelegramChannel] not supported. {"exception":"[object] (InvalidArgumentException(code: 0): Driver [NotificationChannels\\Telegram\\TelegramChannel] not supported. at /home/mauro/www/queuey/vendor/laravel/framework/src/Illuminate/Support/Manager.php:119)

What i'm trying to do is to send a simple notification when a form is filled.

```
`
namespace App\Notifications;

use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Notifications\Messages\MailMessage;

use NotificationChannels\Telegram\TelegramChannel;
use NotificationChannels\Telegram\TelegramMessage;

use Illuminate\Notifications\Notification;

Use Log;

class MerchantLead extends Notification implements ShouldQueue
{
    use Queueable;
    
    protected $message;
    /**
    * Create a new notification instance.
    *
    * @return void
    */
    public function __construct($message)
    {
        $this->message = $message;
    }
    
    /**
    * Get the notification's delivery channels.
    *
    * @param  mixed  $notifiable
    * @return array
    */
    public function via($notifiable)
    {
        return [TelegramChannel::class];
    }
    
    /**
    * Get the mail representation of the notification.
    *
    * @param  mixed  $notifiable
    * @return \Illuminate\Notifications\Messages\MailMessage
    */
    public function toMail($notifiable)
    {
        Log::info('[MERCHANT-LEAD] '. json_encode($this->message));
        return (new MailMessage)
        ->subject('Nuova Richiesta di Contatto da un esercente')
        ->line($this->message['firstname'] . ' ' . $this->message['lastname'] .' ha richiesto informazioni su QApp')
        ->line('Email: ' . $this->message['email'])
        ->line('Phone: ' . $this->message['phone'])
        ->line('Messaggio: ' . $this->message['text']);
        
        
    }
    
    public function toTelegram($notifiable)
    {
        
        $message = "<b>{$this->message['firstname']} {$this->message['lastname']}</b> ha richiesto informazioni su QApp\n";
        $message .= "Email: " . $this->message['email'] ."\n";
        $message .= 'Phone: ' . $this->message['phone']."\n";
        $message .= 'Messaggio: ' . $this->message['text']."\n";
        
        return TelegramMessage::create()
        ->options(['parse_mode' => 'HTML'])
        ->to(env('TELEGRAM_BOT_NOTIFICATION_GROUP_ID'))
        ->content($message);
    }
    
    /**
    * Get the array representation of the notification.
    *
    * @param  mixed  $notifiable
    * @return array
    */
    public function toArray($notifiable)
    {
        return [
            //
        ];
    }
}
`
```

if i remove the "implement ShouldQueue" the message is sent properly, while if i set the queue the exception above is thrown.

Somebody had a similar problem or an advise on this?

**Comment by irazasyed** [comment]
Hi,

I just tried this in my code and it works fine with or without the queues.

Maybe share your other code that invokes this notification? Could be an issue there.

**Comment by ulul** [comment]
I have the same problem, how you solve this problem?

**Comment by mauronex** [comment]
> I have the same problem in Laravel 8, how you solve this problem?

In my case, since i was using Horizon to dispatch jobs i had to just terminate and re-start the worker.
It should be also for the queue worker even if you are not using Horizon

**Comment by j33tmane** [comment]
> I have the same problem in Laravel 8, how you solve this problem?

use NotificationChannels\Telegram\TelegramChannel;
use NotificationChannels\Telegram\TelegramMessage;

copy these lines to your notification under App/Notifications/YourNotification.php

**Comment by Yeleup** [comment]
I have the same problem in Laravel 10, how you solve this problem?

**php artisan queue:restart** did not help
