### ISSUE TITLE
How to use token which is in the database? 

### ISSUE THREAD

**Issue by SergeyKuzmenko** [laravel-notification-channels/telegram#77]
Hello!  Tell me how to use telegram token which is in the database?

**Comment by irazasyed** [comment]
Hey @SergeyKuzmenko, You can use the `config` method to set a token from your database, just make sure it's set before any notification is sent for it to reflect.

Example

```php
$token = 'YOUR TOKEN FROM DATABASE';

config(['services.telegram-bot-api.token' => $token]);
```
