### ISSUE TITLE
How to disable markdown parsing?

### ISSUE THREAD

**Issue by rst630** [laravel-notification-channels/telegram#79]
Sometime I got 400 response from telegram api because message contains some bad symbols (I sending json logs)

Im escaping _ `new TelegramAdmin(str_replace('_','\_',$msg)` but something else breaking it when parsing $msg

**Comment by irazasyed** [comment]
Try using `options(['parse_mode' => ''])` method.

But if you're sending logs, you should consider wrapping them in backticks, so they're formatted when sent to you. Ex: ` ``` LOGS ``` `

**Comment by rst630** [comment]
`content('')->options(['parse_mode' => ''])` helped. Thanks!
