### ISSUE TITLE
Feature; for send from blade template

### ISSUE THREAD

**Issue by tomswinkels** [laravel-notification-channels/telegram#82]
Normally you do;

```php
        return TelegramMessage::create()
            ->options([
                'parse_mode' => 'HTML'
            ])
            ->content('content);
```

But i think sometimes is nicer that you can use a template!

```php
        return TelegramMessage::create()
            ->options([
                'parse_mode' => 'HTML'
            ])
            ->view('telegram.new-user',$data);
```

For now i do;

```php
        $telegramView = View::make('telegram.new-user', $data);

        return TelegramMessage::create()
            ->options([
                'parse_mode' => 'HTML',
                'disable_web_page_preview' => true
            ])
            ->content($telegramView->render());
```

Maybe this is a nice feature :)

**Comment by irazasyed** [comment]
Interesting idea, maybe you could PR? Won't be able to work on this anytime soon due to ongoing projects.

In addition to that, maybe we could also support markdown files. Like nothing fancy, just give the markdown file path or the content of the blade file could be in markdown format and it'll work.

**Comment by Cannonb4ll** [comment]
```php
        return TelegramMessage::create()
            ->options([
                'parse_mode' => 'HTML'
            ])
            ->content(view('my-view', $data)->render());
```

**Comment by irazasyed** [comment]
New https://github.com/laravel-notification-channels/telegram/commit/9c0d8d5dd51801071819ceabfb24577c4aaf39d2: `view($view, $data, $mergeData)`

View files can be of one of these types: `blade.php`, `php`, `html`.

It supports blade templates and Markdown/HTML syntax (limited to what Telegram accepts).
