### ISSUE TITLE
"bot-token per-notification" and ShouldQueue interface

### ISSUE THREAD

**Issue by camiant** [laravel-notification-channels/telegram#84]
when you need to queue notifications (implementing `ShouldQueue` interface) which use bot-token different from the default one (declared on  `config('services.telegram-bot-api.token')`), there's no way to specify a custom one as an optional additional parameter.

**Comment by irazasyed** [comment]
This has been implemented in https://github.com/laravel-notification-channels/telegram/commit/cfa3d1f8df8afeadb3191f6b772efef11b5701fb. You can now use `token($token)` method per notification. 

Please test and report back any issues. Thanks!
