### ISSUE TITLE
Bot messages are not delivered and no error message

### ISSUE THREAD

**Issue by olaseyo** [laravel-notification-channels/telegram#87]
public function toTelegram($data)
  {
    return TelegramMessage::create()
    ->content($data);
  }
Please help!

**Comment by emrecanozkok** [comment]
now me too,i cant send message with chad id

**Comment by olaseyo** [comment]
> now me too,i cant send message with chad id

Got mine working. can i see your code and how did you get your chatid?

**Comment by irazasyed** [comment]
Please share your complete code and steps to reproduce.
