### ISSUE TITLE
Telegram responded with an error `400 - Bad Request: chat not found`

### ISSUE THREAD

**Issue by mdtanjilhasan** [laravel-notification-channels/telegram#92]
![1](https://user-images.githubusercontent.com/42772759/94112748-b2054d80-fe67-11ea-9292-586a9e86217c.png)
![2](https://user-images.githubusercontent.com/42772759/94112752-b3cf1100-fe67-11ea-86ff-a61107a537f4.png)
![3](https://user-images.githubusercontent.com/42772759/94112754-b3cf1100-fe67-11ea-89b7-e72bd9949bf0.png)
![4](https://user-images.githubusercontent.com/42772759/94112756-b467a780-fe67-11ea-886a-c475ea8eac19.png)
![5](https://user-images.githubusercontent.com/42772759/94112757-b5003e00-fe67-11ea-942b-9e7580bf5f9a.png)
![6](https://user-images.githubusercontent.com/42772759/94112760-b598d480-fe67-11ea-93f3-d14984f3a99c.png)

**Comment by irazasyed** [comment]
Please check the bot token is correct and that you've messaged & obtained the chat id from the same bot which is configured.

Chat IDs are unique to each bot for every user and cannot be shared/reused.

**Comment by mdtanjilhasan** [comment]
I have tried with another bot chat id, i have got same error. The token is
correct cause, i can send text via bot api.

**Comment by irazasyed** [comment]
You can't use "another bot" chat id. I just tested this on a fresh project and I can send the notification without issues.

Here's how it should be:

- Bot A Token is configured.
- You message Bot A.
- You save the chat ID of the user gotten to your Bot A.
- You use that chat ID to send notifications from your Bot A.

Do not mix with different bots.

Also, what version of Laravel and this channel lib you're using?

**Comment by mdtanjilhasan** [comment]
I have done the steps appropriately. Laravel 7 and latest version on the
package

**Comment by winter-ice** [comment]
Same issue here.

**Comment by PunyFlash** [comment]
Telegram bots can't send messages to user, if that user hasn't started conversation with bot yet, or bot is not present in chat (if it's a group chat). This issue is not related to the library, this is simply Telegram restriction, so that bots can't spam users without their permission.

**Comment by winter-ice** [comment]
> Telegram bots can't send messages to user, if that user hasn't started conversation with bot yet, or bot is not present in chat (if it's a group chat). This issue is not related to the library, this is simply Telegram restriction, so that bots can't spam users without their permission.

Just use Http request can send messages,but use this package not work

**Comment by gorkau** [comment]
You can use a Telegram bot named @userinfobot to get the ID of a user. Beware, there are many accounts named @userinfobot, use them only if they are a bot.

**Comment by Ryllaz** [comment]
> > Telegram bots can't send messages to user, if that user hasn't started conversation with bot yet, or bot is not present in chat (if it's a group chat). This issue is not related to the library, this is simply Telegram restriction, so that bots can't spam users without their permission.
> 
> Just use Http request can send messages,but use this package not work

Same issue. 

@gorkau your advice working, sending to user_id works fine.

But I think that package should send messages by user's login as well

**Comment by nguyentranchung** [comment]
In group, you type any message begin with /, ex: /hellobot

Then open in web browser

https://api.telegram.org/bot<Your Bot Token>/getUpdates

Find /hellobot and you can see:
![Selection_004](https://user-images.githubusercontent.com/9611224/128153236-a47622e1-e3ba-4574-868a-7c84f8c76459.png)

You can take chat id

**Comment by daviddprtma** [comment]
> https://api.telegram.org/bot/getUpdates

Today I get the same issue like as the authors issue. I want to know about where can I get my chatID? is it in my telegram bot?

**Comment by daviddprtma** [comment]
> Please check the bot token is correct and that you've messaged & obtained the chat id from the same bot which is configured.
> 
> Chat IDs are unique to each bot for every user and cannot be shared/reused.

Today I get the same issue like as the authors issue. I want to know about where can I get my chatID? is it in my telegram bot?
