### ISSUE TITLE
not working with laravel 8.x

### ISSUE THREAD

**Issue by ProMasoud** [laravel-notification-channels/telegram#93]
Hi,

Today I want to upgrade my laravel from 7 to newest Laravel 8. but received an error by composer that this package is not support Laravel 8.

**Comment by irazasyed** [comment]
Hey!

I'm not sure which version you're trying but Laravel 8.x is already supported. See this https://github.com/laravel-notification-channels/telegram/releases/tag/0.5.0

**Comment by irazasyed** [comment]
Try the above and share the error message if you still face the issue. I've tested it before releasing that version.
