### ISSUE TITLE
Markdown error

### ISSUE THREAD

**Issue by awkaw** [laravel-notification-channels/telegram#97]
Bold text must be specified as `**bold**` (two '*' characters). Don't `*Bold*`! https://www.markdownguide.org/basic-syntax/

**Comment by irazasyed** [comment]
It's as per Telegram's official supported [formatting options](https://core.telegram.org/bots/api#formatting-options) for [Markdown](https://core.telegram.org/bots/api#markdown-style) mode as it works based on one char of asterisks.
