### ISSUE TITLE
Is it possible to return TelegramMessage and TelegramFile at same time ?

### ISSUE THREAD

**Issue by rifkyariy** [laravel-notification-channels/telegram#99]

**Comment by PunyFlash** [comment]
No it's not. Library serializes only one `JsonSerializable` output. By the way, it is easy to implement if you refactor [TelegramChannel::send](https://github.com/laravel-notification-channels/telegram/blob/2cedb10b78219cc91a285eaa5a3de0db405cc207/src/TelegramChannel.php#L37) function.

**Comment by rifkyariy** [comment]
okay, thanks for answering this
